Update owners
openshift/gcp-project-operator pull request #196
Opened 2023-06-14 14:57 UTC by typeid

### What type of PR is this? 
Update owner list to contain team orange and current contributors

2023-06-14 16:19 UTC, mjlshen requested changes

2023-06-14 16:19 UTC, mjlshen commented on OWNERS
> +- mjlshen
```suggestion
```

I'm not ready to be an approver in this repo :D

2023-06-14 17:15 UTC, mjlshen reviewed
/lgtm

2023-06-21 08:30 UTC, NautiluX reviewed
/lgtm

2023-06-21 08:34 UTC, merged