Format code and update manifests
openshift/gcp-project-operator pull request #99
Opened 2020-09-08 18:10 UTC by yeya24

Signed-off-by: Ben Ye <yb532204897@gmail.com>

### What type of PR is this? 
_(bug/feature/cleanup/docs/design/test/chore/refactor..)_

### What this PR does / why we need it:

Format code and update manifests based on API changes.

### Which issue(s) this PR fixes(can be a reference to existing issue or jira/bz):

_Fixes #_

### Special notes for your reviewer:

### Is it a breaking change or backward compatible?

### Pre-checks:
- [ ] manually tested latest changes against crc/k8s
- [ ] run the `make coverage` command to generate new calculated coverage

2020-09-09 17:31 UTC, rafael-azevedo requested changes

2020-09-09 17:31 UTC, rafael-azevedo commented on deploy/crds/gcp_v1alpha1_projectclaim_crd.yaml
> +              required:
remove required field here

2020-09-09 17:31 UTC, rafael-azevedo commented on deploy/crds/gcp_v1alpha1_projectreference_crd.yaml
> +              required:
remove required field here

2020-09-09 17:31 UTC, rafael-azevedo commented on deploy/crds/gcp_v1alpha1_projectreference_crd.yaml
> +          required:
remove required field here

2020-09-09 17:31 UTC, rafael-azevedo commented on deploy/crds/gcp_v1alpha1_projectreference_crd.yaml
> +      required:
remove required field here

2020-09-09 18:36 UTC, yeya24 commented on deploy/crds/gcp_v1alpha1_projectclaim_crd.yaml
> +              required:
It is needed.

2020-09-09 18:36 UTC, yeya24 commented on deploy/crds/gcp_v1alpha1_projectreference_crd.yaml
> +              required:
It is needed.

2020-09-10 07:05 UTC, RiRa12621 commented
@yeya24 can you please fill out the template, so it's a bit more obvious what's going to happen in this PR before looking at the code itself?

2020-09-10 12:43 UTC, yeya24 commented
@RiRa12621 Sorry for the inconvenience, I just updated the description. Thanks!

2020-09-10 13:59 UTC, rafael-azevedo approved these changes

2020-09-10 14:00 UTC, rafael-azevedo commented
/lgtm

2020-09-10 14:00 UTC, merged